### ISSUE TITLE
Refactor types creation in NWB Model Interpreter

### ISSUE THREAD

**Issue by tarelli** [openworm/org.geppetto.model.nwb#7]
Currently we are creating a new type for every sweep and for every signal. We need to have only one type of type Sweep and only one type of type Signal. These two types are then reused by all sweeps and all signals (both stimulus and response) in the model.
- [x] Review design
  ![Image](https://www.lucidchart.com/publicSegments/view/627bdb77-6f3b-4063-aaa8-9f35505ec6c6/image.png)
- [x] Refactor creation of types
- [x] Use CompositeValue to specify values for variables nested inside a CompositeType
- [ ] Add to an Instance .getValue() which returns whatever is in the composite value at the higher level Check with @gidili design for this
- [ ] Update unit tests
- [ ] Make sure everything works as before

**Comment by niteshthali08** [comment]
@tarelli : for composite value, you want me to create it like the one below right ?
Value compositeValue = ValuesFactory.eINSTANCE.createComposite();
Could you please give me an example as how to put string and its value inside this stringValue map ?

**Comment by niteshthali08** [comment]
Is this the correct way ?
((Composite) compositeValue).getValue().put("stimulus.recording", importValue);

**Comment by tarelli** [comment]
@niteshthali08 yep 👍

**Comment by gidili** [comment]
@tarelli had a chat with @niteshthali08 about this.

Just trying to make sure I understand the getValue functionality for the instances, is the idea to look into the parents until something is found with a composite value that ends with the same path as the instance path?

For example for an instance of path sweepX.stimulus.recording if you do .getValue you should get back the stimulus.recording value from the composite value that's returned if you do getValue on the sweepX variable (sweepX.getVariable().getValue(), look inside the composite value and get from the map the  'stimulus.recording' item)?

**Comment by tarelli** [comment]
Yup

**Comment by gidili** [comment]
🙈 

Is this to happen only if there is not already a value for the variable associated to that instance we do getValue on, or regardless?

**Comment by tarelli** [comment]
Regardless, the value if it exists at the type level would still be only a
default to option but if a specific value for that instance is specified
that takes the priority. We should have a smart way to avoid traversing
everything every time we do getValue, something like tracking whether a
composite value has been provided or not to avoid traversing in most cases.

**Comment by gidili** [comment]
@tarelli if you want to put a flag in every instance saying "there is a composite value for you somewhere in your parents so it's ok to traverse" you have to traverse everything when you are creating them to set the flags. 

At that point (since you are traversing) wouldn't it be easier to actually add a reference to the composite value itself (or even to the specific value in the composite value that is relevant for that instance)?

The alternative is that every time we do getValue we traverse all parents in search of a composite value with an item in the map that relates to the instance that does getValue. This would take "more" when you do getValue if the instance path is really long, but it would avoid doing it upfront when loading the model and building the instance tree.

**Comment by tarelli** [comment]
I was thinking more something along the lines of whenever we create a
composite value object client side we store it's path in a map and when we
do getValue we check in the map if there is a composite value whose path is
the beginning of the instance path we are calling getValue on, something
like that.

**Comment by gidili** [comment]
@niteshthali08 based on the discussion above,  I think we could try the following:

- when composite values are created client side, store a list of the instance paths for which we have composite values. I would store this list in the ModelFactory unless @tarelli has a better place in mind
- when doing getValue on an instance, check if there is a partial match of paths (starts with the same thing) between the stuff stored in the list of paths with composite values and the path of the given instance we do getValue on
   - if there is a composite value, then implement the algorithm of satan doing recursion into parent instances (getParent) until the path of the parent matches the path we found, and then go into the composite value and get what's needed based on the rest of the path of the instance we did getValue on
   - if there is not a composite value, return nothing (or an empty whatever consistent with what's there now)

Alternatively, while we are at it, instead of storing a list we could store a map with paths as keys and a reference (not a duplicate!) to the actual composite value. This way you can retrieve the composite value directly and avoid to write the algorithm that does the recursion altogether. 

@tarelli how does that sound?

@niteshthali08 any help you can ask here and/or we can schedule a hangout chat!

**Comment by tarelli** [comment]
Map FTW

**Comment by niteshthali08** [comment]
@gidili : I will work on it and let you know if i get stuck at some point. 
@tarelli - I wanted to discuss about implementation of [this](https://github.com/openworm/org.geppetto/issues/499#event-673522385) ticket with you. It would be great if you can schedule a small meeting for the same.

**Comment by tarelli** [comment]
@niteshthali08 hey Nitesh, any update on this? Thanks!
